#+title: Terrain Model Processing with Machine Learning
#+AUTHOR: Struan Robertson @@latex:\\@@ BSc (Hons) Applied Computing
#+DATE: May 2023
#+BIBLIOGRAPHY: library.bib
#+OPTIONS: toc:nil
#+cite_export: biblatex

#+LaTeX_CLASS: article
#+LaTeX_CLASS_OPTIONS: [twocolumn]
# Styles

# Basic Packages
#+LaTeX_HEADER: \usepackage{balance}
#+LaTeX_HEADER: \usepackage{graphics}
#+LaTeX_HEADER: \usepackage{txfonts}
#+LaTeX_HEADER: \usepackage{times}
#+LaTeX_HEADER: \usepackage{color}
#+LaTeX_HEADER: \usepackage{textcomp}
#+LaTeX_HEADER: \usepackage{booktabs}
#+LaTeX_HEADER: \usepackage{todonotes}
#+LaTeX_HEADER: \usepackage{float}
#+LaTeX_HEADER: \usepackage{url}
#+LaTeX_HEADER: \usepackage{titling}
#+LaTeX_HEADER: \usepackage[pdftex]{hyperref}

# Font sizess
#+LaTeX_HEADER: \usepackage{sectsty}
#+LaTeX_HEADER: \sectionfont{\Large}
#+LaTeX_HEADER: \subsectionfont{\large}
#+LaTeX_HEADER: \subsubsectionfont{\large}
#+LaTeX_HEADER: \paragraphfont{\normalsize}

# Positioning
#+LaTeX_HEADER: \setlength{\parindent}{0em}
#+LaTeX_HEADER: \setlength{\parskip}{1em}
#+LaTeX_HEADER: \setlength{\columnsep}{2em}
#+LaTeX_HEADER: \setlength{\droptitle}{-10em}

# Define global style for URLs
#+LaTeX_HEADER: \makeatletter
#+LaTeX_HEADER: \def\url@leostyle{%
#+LaTeX_HEADER:     \@ifundefined{selectfont}{\def\UrlFont{\sf}}{\def\UrlFont{\small\bf\ttfamily}}}
#+LaTeX_HEADER: \makeatother
#+LaTeX_HEADER: \urlstyle{leo}

#+LATEX: \begin{abstract}

With the launch of the lunar orbiter laser altimeter (LOLA) on NASA's lunar reconnaissance orbiter (LRO), a large amount of high-resolution digital elevation maps (DEMs) have been constructed, providing a precise topographical model of the moons surface.
These DEMs are prone to voids containing no data, making the map less reliable for scientific purposes and future moon missions.
This paper uses a machine learning model to allow for the technique of image inpainting to be used with lunar DEMs.
Image inpainting uses pixel data from an image to generate missing data to fill a void.
DEMs can be thought of mathematically as identical to a single channel (greyscale) image, a two-dimensional array with "pixel" values corresponding to height, and so the technique of image inpainting can be easily applied to DEMs.
A Generative Adversarial Network (GAN) based on a fully convolutional architecture was used for the inpainting.

#+LATEX: \end{abstract}

* Introduction

This section should introduce the project.
Citation: [cite:@wengGANWGAN2019]
It should include an explanation of the problem and the objectives of the project.
It is very important to give a clear description of what the project is actually intended to do, preferably in non-technical terms.
The report as a whole should include a clear description of the lifecycle stages undertaken and must describe the use of appropriate tools to support the development process.
It should give a full and accurate description of the work done and achievements made, together with complete software documentation.
Every effort should be made to provide a professional, quality description of the work.
Proofread carefully for grammatical, spelling and punctuation errors or inconsistencies BBC.
The report should be formatted as a justified, double-column, single-spaced, 10pt Times New Roman font document using an appropriate word processing system such as Microsoft Word, OpenOffice Writer or LaTeX and converted to a PDF file.
The length of the report is likely to depend, for example, on the number of images included.
As a guide, you should aim for about 20 pages, with 15 pages regarded as a lower limit and 35 as an upper limit.
What is required is quality rather than quantity.
The general layout of the report should follow this example document although the number of sections and their headings will vary from project to project.
The report should be written in a formal style: it is neither a diary nor a magazine article.
All pages should be numbered.
All references should be cited in the main body of the report and a standard referencing format (such as IEEE or Harvard style) should be adopted Wilde.
The report should demonstrate that the student has used appropriate tools to support the development process and that verification and validation have been applied at all stages

** Export Tests

*Bold*
/Italics/
=Mono=
~Code~
_Underline_
+Crossed+

The subsections can hold various information.
Use subsections to break up your document and make it easier to read.

You can include lists with bullet points:
- /Item 1/
- *Item 2*
- Item 3
- Item 4

#+PRINT_BIBLIOGRAPHY:
