#+title: Terrain Model Processing with Machine Learning
#+AUTHOR: Struan Robertson @@latex:\\@@ BSc (Hons) Applied Computing
#+DATE: May 2023
#+BIBLIOGRAPHY: library.bib
#+OPTIONS: toc:nil
#+LANGUAGE: en-gb
#+cite_export: biblatex

#+LaTeX_CLASS: article
#+LaTeX_CLASS_OPTIONS: [twocolumn]
# Styles

# Basic Packages
#+LaTeX_HEADER: \usepackage{balance}
#+LaTeX_HEADER: \usepackage{graphics}
#+LaTeX_HEADER: \usepackage{txfonts}
#+LaTeX_HEADER: \usepackage{times}
#+LaTeX_HEADER: \usepackage{color}
#+LaTeX_HEADER: \usepackage{textcomp}
#+LaTeX_HEADER: \usepackage{booktabs}
#+LaTeX_HEADER: \usepackage{todonotes}
#+LaTeX_HEADER: \usepackage{float}
#+LaTeX_HEADER: \usepackage{url}
#+LaTeX_HEADER: \usepackage{titling}
#+LaTeX_HEADER: \usepackage[pdftex]{hyperref}
#+LaTeX_HEADER: \usepackage[british]{babel}

# Font sizes
#+LaTeX_HEADER: \usepackage{sectsty}
#+LaTeX_HEADER: \sectionfont{\Large}
#+LaTeX_HEADER: \subsectionfont{\large}
#+LaTeX_HEADER: \subsubsectionfont{\large}
#+LaTeX_HEADER: \paragraphfont{\normalsize}

# Positioning
#+LaTeX_HEADER: \setlength{\parindent}{0em}
#+LaTeX_HEADER: \setlength{\parskip}{1em}
#+LaTeX_HEADER: \setlength{\columnsep}{2em}
#+LaTeX_HEADER: \setlength{\droptitle}{-10em}

# Define global style for URLs
#+LaTeX_HEADER: \makeatletter
#+LaTeX_HEADER: \def\url@leostyle{%
#+LaTeX_HEADER:     \@ifundefined{selectfont}{\def\UrlFont{\sf}}{\def\UrlFont{\small\bf\ttfamily}}}
#+LaTeX_HEADER: \makeatother
#+LaTeX_HEADER: \urlstyle{leo}

#+LaTeX_HEADER: \usepackage[
#+LaTeX_HEADER:    %backend=biber,
#+LaTeX_HEADER:    natbib=true,
#+LaTeX_HEADER:    style=numeric,
#+LaTeX_HEADER:    sorting=none
#+LaTeX_HEADER: ]{biblatex}

#+LaTeX_HEADER:\bibliographystyle{ACM-Reference-Format}

#+LATEX: \begin{abstract}

With the launch of the lunar orbiter laser altimeter (LOLA) on NASA's lunar reconnaissance orbiter (LRO), a large amount of high-resolution digital elevation maps (DEMs) have been constructed, providing a precise topographical model of the moons surface.
These DEMs are prone to voids containing no data, making the map less reliable for scientific purposes and future moon missions.
This paper uses a machine learning model to allow for the technique of image inpainting to be used with lunar DEMs.
Image inpainting uses pixel data from an image to generate missing data to fill a void.
DEMs can be thought of mathematically as identical to a single channel (greyscale) image, a two-dimensional array with "pixel" values corresponding to height, and so the technique of image inpainting can be easily applied to DEMs.
A Generative Adversarial Network (GAN) based on a fully convolutional architecture was used for the inpainting.


#+LATEX: \end{abstract}

* Introduction

Sensory data from the Lunar Orbiter Laser Altimeter (LOLA) and Lunar Reconnaissance Orbiter Camera (LROC) has been used for the construction of Lunar digital elevation models (DEMs) since the launch of the Lunar Reconnaissance Orbiter (LRO) in 2009.
LRO has several primary objectives as part of a series of robotic missions that aim to pave the way for a permanent human presence on the Moon, including determining the global topography of the lunar surface at meter-scale resolution.
Topographical data from LOLA and LROC will be used to facilitate the selection of future landing sites, so accuracy and completeness are essential.
[cite:@chinLunarReconnaissanceOrbiter2007]

The LRO is in a polar orbit around the moon, scanning the surface in swathes 50 to 60m wide, with an average separation ranging between 1.2km and 200m depending on the position of LRO in orbit.
LOLA uses a laser altimeter to measure the distance from LRO to the lunar surface at 5 different spots simultaneously, providing DEMs ranging from ~30m resolution at the equator to ~5m resolution at the poles. [cite:@smithLunarOrbiterLaser2010].
LROC uses two narrow-angle cameras (NACs) to collect stereo observations at a resolution of 0.5 to 1.5 m per pixel.
These high resolution images can be used to generate high resolution (~5m at the equator) DEMS, referred to as NAC DEMs [cite:@tranGeneratingDigitalTerrain2010].

Both LOLA and NAC dems are prone to no-data voids resulting from shadowed regions (NAC) or terrain features blocking the return of the laser altimeter (LOLA).
As the LRO has a polar orbit, data is recorded in strips, which must be joined together to create larger DEMs. These strips are not immediately adjacent to each other, resulting in a no-data void between strips.
Reconstructing these no-data voids is non-trivial, with Park and Choi [cite:@parkNeuralProcessApproach2021]  noting the following challenges:
 - NAC DEMs require high-resolution reconstruction methodology
 - The reconstruction algorithm must be reliable since it can affect related lunar studies or exploration missions
 - NAC DEMs are large and high-resolution area maps, thus a scalable approach should be applied

Traditional algorithmic methods for correcting no-data voids within DEMs include inverse distance weight method (IDW), local polynomial interpolation method (LPI), spline with tension method (ST) and other algorithms to interpolate the elevation sampling points. Interpolation methods use the neighboring elevation values for void infilling, thus performance is directly proportional to the size of the void. Voids of any significant size result in interpolation methods returning inaccurate reconstruction results.  [cite:@reuterEvaluationVoidFilling2007]

Image inpainting

* Background

* Specification

* Design

* Implementation and Testing

* Evaluation / Testing

* Description of the final product

* Appraisal

* Summary and Conclusions

* Future Work

#+LATEX: \section*{Acknowledgements}

#+PRINT_BIBLIOGRAPHY:

#+LATEX: \section*{Appendices}
